spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/order-service,classpath:/product-service,classpath:/saga-service

