spring:
  application:
    name: order-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8085
    stream:
      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:29092
        bindings:
          submitOrder-out-0:
            producer:
              configuration:
                enable:
                  idempotance: true
                acks: all
                retries: 3
      bindings:
        submitOrder-out-0:
          destination: order_topic
        orderSubmitFailed-in-0:
          destination: order_failed_topic
          group: order_failed_group
    function:
      definition: orderSubmitFailed
  config:
    import: optional:configserver:http://localhost:8085
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8081

server:
  port: 5001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
    env:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    com.mertalptekin.orderservice.client.ProductClient: DEBUG
    com.mertalptekin.orderservice.controller.OrderController: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

