spring:
  application:
    name: gateway
  # --- REDIS AYARLARI ---
  data:
    redis:
      host: localhost
      port: 6379
      password: Neominal

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/AuthServer
          jwk-set-uri: http://localhost:8180/realms/AuthServer/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: orderClient
              uri: lb://order-service
              predicates:
                - Path=/order-service/api/v1/**
              filters:
                - StripPrefix=1
            - id: productClient
              uri: lb://product-service
              predicates:
                - Path=/product-service/api/v1/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8084

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0


# http://localhost:8084/actuator/circuitbreakers

# Rate Limitter Postman Collection Runner ile test case

# ---------------- LOGGING ----------------
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.data.redis: INFO
    io.github.resilience4j: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html



